// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestingPlatform1;

#nullable disable

namespace TestingPlatform1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251006093852_InitStudents")]
    partial class InitStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TestingPlatform1.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VkProfileLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 10, 6, 14, 38, 52, 345, DateTimeKind.Unspecified).AddTicks(7976), new TimeSpan(0, 5, 0, 0, 0)),
                            Email = "petr11@gmail.com",
                            FirstName = "fear",
                            LastName = "resh",
                            Login = "petr111",
                            MiddleName = "grat",
                            Phone = "79352235412",
                            VkProfileLink = "http://vk.com/petfdgr11221"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 10, 6, 14, 38, 52, 347, DateTimeKind.Unspecified).AddTicks(5099), new TimeSpan(0, 5, 0, 0, 0)),
                            Email = "katya11@gmail.com",
                            FirstName = "fewar",
                            LastName = "reslolh",
                            Login = "katya111",
                            MiddleName = "grherat",
                            Phone = "79357775612",
                            VkProfileLink = "http://vk.com/kathsdha2134"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
